spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/eticket_db?serverTimezone=UTC&characterEncoding=UTF-8&sslMode=DISABLED&createDatabaseIfNotExist=true"
    username: ""
    password: ""
    continueOnError: true
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    hikari:
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  security:
    basic:
      enabled: false
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:
logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
application:
  access-token:
  api-token:
app:
  dropbox:
    access:
      token:
auth0:
  client_id:
  secret:
  management:
    client_id:
    audience:
    secret:

external:
  kat-api:
    appId:
    apiKey: